
ALTER TABLE t_p54886222_design_office_projec.users
ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS telegram VARCHAR(100),
ADD COLUMN IF NOT EXISTS website VARCHAR(300),
ADD COLUMN IF NOT EXISTS work_styles TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS work_objects TEXT DEFAULT '';
